// Local browser QA; run with bundled Playwright and an installed browser.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const http = require('node:http');
const path = require('node:path');
const {chromium} = require(process.env.PLAYWRIGHT_PACKAGE || 'playwright');
(async () => {
  const root=process.cwd();
  const types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png','.pdf':'application/pdf'};
  const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(err,content)=>{if(err){res.writeHead(404);return res.end();}res.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');res.end(content);});});
  await new Promise(resolve=>server.listen(8001,'127.0.0.1',resolve));
  const browser = await chromium.launch({headless:true, executablePath:process.env.SITE_BROWSER});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const missing=[];
  page.on('response',r=>{if(r.status()>=400 && r.url().startsWith('http://127.0.0.1'))missing.push(r.url());});
  await page.goto('http://127.0.0.1:8001', {waitUntil:'networkidle'});
  await page.addStyleTag({content:'html{scroll-behavior:auto!important}'});
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('#metrics-body tr').count(),62);
  assert.equal(await page.locator('.gallery-card').count(),10);
  assert.equal(await page.locator('.gallery-extra, [data-gallery]').count(),0);
  assert.equal(await page.locator('#conditions-body tr').count(),10);
  await page.locator('#metric-type').selectOption('FR');
  assert.equal(await page.locator('#metrics-body tr').count(),26);
  await page.locator('#metric-variant').selectOption('adapted');
  assert.equal(await page.locator('#metrics-body tr').count(),5);
  await page.locator('#metric-type').selectOption('all');
  assert.equal(await page.locator('#metrics-body tr').count(),11);
  await page.locator('#metric-search').fill('Q-ReAlign-mini');
  assert.equal(await page.locator('#metrics-body tr').count(),2);
  await page.locator('#metric-search').fill('');
  await page.locator('#metric-variant').selectOption('all');
  await page.locator('#condition-family').selectOption('Non-diffusion');
  assert.equal(await page.locator('#conditions-body tr').count(),4);
  await page.locator('#condition-factor').selectOption('LR degradation');
  assert.equal(await page.locator('#conditions-body tr').count(),4);
  await page.locator('#condition-family').selectOption('Diffusion');
  await page.locator('#condition-factor').selectOption('SR method');
  await page.locator('.hero-figure [data-zoom]').click();
  assert(await page.locator('#figure-dialog').isVisible());
  await page.keyboard.press('Escape');
  assert(!(await page.locator('#figure-dialog').isVisible()));
  await page.locator('#toggle-pdf').click();
  assert(await page.locator('#pdf-embed').isVisible());
  assert((await page.locator('#pdf-embed iframe').getAttribute('src')).includes('DISRQAD.pdf'));
  await page.locator('#toggle-pdf').click();
  await page.locator('#arxiv-placeholder').click();
  assert((await page.locator('#arxiv-status').textContent()).includes('not public yet'));
  await page.evaluate(()=>document.getElementById('arxiv-status').textContent='arXiv link will be added after publication.');
  await page.evaluate(async()=>{for(const im of document.images){im.loading='eager';}await Promise.all(Array.from(document.images).filter(im=>im.src).map(im=>im.decode().catch(()=>{})));});
  assert.equal(await page.evaluate(()=>Array.from(document.images).filter(im=>im.src&&!im.complete || im.src&&!im.naturalWidth).length),0);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:'tmp/desktop-hero.png'});
  await page.screenshot({path:'tmp/desktop-full.png',fullPage:true});
  await page.locator('#benchmark').scrollIntoViewIfNeeded();
  await page.screenshot({path:'tmp/desktop-benchmark.png'});
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>scrollTo(0,0));
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:'tmp/mobile-hero.png'});
  await page.screenshot({path:'tmp/mobile-full.png',fullPage:true});
  await page.setViewportSize({width:320,height:720});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.deepEqual(errors,[]);
  assert.deepEqual(missing,[]);
  const result={metricRows:62,conditionRows:28,figures:10,checks:'filters, search, paper-only gallery, keyboard lightbox, PDF viewer, image loading, no overflow at 1440/390/320px, no JS errors or missing local requests'};
  fs.writeFileSync('tmp/qa.json',JSON.stringify(result,null,2));
  console.log(JSON.stringify(result));
  await browser.close();
  server.close();
})().catch(e=>{console.error(e);process.exit(1);});
